name: CD pipeline

on:
    workflow_run:
        workflows: ["CI pipeline"]
        types:
          - completed

jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - name: Pull the Docker Image from Docker Hub
      run: sudo docker pull divmittal04/occasio-backend:latest

    - name: Stop and Remove the Old Docker Container
      run: sudo docker rm -f occasio-backend-container || true

    - name: Run the New Docker Container
      run: |
        sudo docker run -d -p 9002:9002 \
          --name occasio-backend-container \
          -e NODE_ENV=development \
          divmittal04/occasio-backend:latest

    - name: Verify Deployment
      run: |
        for i in {1..10}; do
          if curl -f http://localhost:9002/health; then
            echo "Server is up!";
            exit 0;
          fi;
          echo "Waiting for server...";
          sleep 5;
        done;
        echo "Server did not start in time.";
        exit 1;

    - name: Check Container Logs on Failure
      if: failure()
      run: sudo docker logs occasio-backend-container
